/* automatically generated by rust-bindgen 0.72.1 */

pub const EVMC_ABI_VERSION: _bindgen_ty_1 = 12;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct evmc_bytes32 {
    pub bytes: [u8; 32usize],
}
pub type evmc_uint256be = evmc_bytes32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct evmc_address {
    pub bytes: [u8; 20usize],
}
pub const EVMC_CALL: evmc_call_kind = 0;
pub const EVMC_DELEGATECALL: evmc_call_kind = 1;
pub const EVMC_CALLCODE: evmc_call_kind = 2;
pub const EVMC_CREATE: evmc_call_kind = 3;
pub const EVMC_CREATE2: evmc_call_kind = 4;
pub type evmc_call_kind = ::std::os::raw::c_uint;
pub const EVMC_STATIC: evmc_flags = 1;
pub const EVMC_DELEGATED: evmc_flags = 2;
pub type evmc_flags = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct evmc_message {
    pub kind: evmc_call_kind,
    pub flags: u32,
    pub depth: i32,
    pub gas: i64,
    pub recipient: evmc_address,
    pub sender: evmc_address,
    pub input_data: *const u8,
    pub input_size: usize,
    pub value: evmc_uint256be,
    pub create2_salt: evmc_bytes32,
    pub code_address: evmc_address,
    pub code: *const u8,
    pub code_size: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct evmc_tx_context {
    pub tx_gas_price: evmc_uint256be,
    pub tx_origin: evmc_address,
    pub block_coinbase: evmc_address,
    pub block_number: i64,
    pub block_timestamp: i64,
    pub block_gas_limit: i64,
    pub block_prev_randao: evmc_uint256be,
    pub chain_id: evmc_uint256be,
    pub block_base_fee: evmc_uint256be,
    pub blob_base_fee: evmc_uint256be,
    pub blob_hashes: *const evmc_bytes32,
    pub blob_hashes_count: usize,
    pub block_slot_number: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct evmc_host_context {
    _unused: [u8; 0],
}
pub type evmc_get_tx_context_fn =
    ::std::option::Option<unsafe extern "C" fn(context: *mut evmc_host_context) -> evmc_tx_context>;
pub type evmc_get_block_hash_fn = ::std::option::Option<
    unsafe extern "C" fn(context: *mut evmc_host_context, number: i64) -> evmc_bytes32,
>;
pub const EVMC_SUCCESS: evmc_status_code = 0;
pub const EVMC_FAILURE: evmc_status_code = 1;
pub const EVMC_REVERT: evmc_status_code = 2;
pub const EVMC_OUT_OF_GAS: evmc_status_code = 3;
pub const EVMC_INVALID_INSTRUCTION: evmc_status_code = 4;
pub const EVMC_UNDEFINED_INSTRUCTION: evmc_status_code = 5;
pub const EVMC_STACK_OVERFLOW: evmc_status_code = 6;
pub const EVMC_STACK_UNDERFLOW: evmc_status_code = 7;
pub const EVMC_BAD_JUMP_DESTINATION: evmc_status_code = 8;
pub const EVMC_INVALID_MEMORY_ACCESS: evmc_status_code = 9;
pub const EVMC_CALL_DEPTH_EXCEEDED: evmc_status_code = 10;
pub const EVMC_STATIC_MODE_VIOLATION: evmc_status_code = 11;
pub const EVMC_PRECOMPILE_FAILURE: evmc_status_code = 12;
pub const EVMC_CONTRACT_VALIDATION_FAILURE: evmc_status_code = 13;
pub const EVMC_ARGUMENT_OUT_OF_RANGE: evmc_status_code = 14;
pub const EVMC_WASM_UNREACHABLE_INSTRUCTION: evmc_status_code = 15;
pub const EVMC_WASM_TRAP: evmc_status_code = 16;
pub const EVMC_INSUFFICIENT_BALANCE: evmc_status_code = 17;
pub const EVMC_INTERNAL_ERROR: evmc_status_code = -1;
pub const EVMC_REJECTED: evmc_status_code = -2;
pub const EVMC_OUT_OF_MEMORY: evmc_status_code = -3;
pub type evmc_status_code = ::std::os::raw::c_int;
pub type evmc_release_result_fn =
    ::std::option::Option<unsafe extern "C" fn(result: *const evmc_result)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct evmc_result {
    pub status_code: evmc_status_code,
    pub gas_left: i64,
    pub gas_refund: i64,
    pub output_data: *const u8,
    pub output_size: usize,
    pub release: evmc_release_result_fn,
    pub create_address: evmc_address,
    pub padding: [u8; 4usize],
}
pub type evmc_account_exists_fn = ::std::option::Option<
    unsafe extern "C" fn(context: *mut evmc_host_context, address: *const evmc_address) -> bool,
>;
pub type evmc_get_storage_fn = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut evmc_host_context,
        address: *const evmc_address,
        key: *const evmc_bytes32,
    ) -> evmc_bytes32,
>;
pub type evmc_get_transient_storage_fn = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut evmc_host_context,
        address: *const evmc_address,
        key: *const evmc_bytes32,
    ) -> evmc_bytes32,
>;
pub const EVMC_STORAGE_ASSIGNED: evmc_storage_status = 0;
pub const EVMC_STORAGE_ADDED: evmc_storage_status = 1;
pub const EVMC_STORAGE_DELETED: evmc_storage_status = 2;
pub const EVMC_STORAGE_MODIFIED: evmc_storage_status = 3;
pub const EVMC_STORAGE_DELETED_ADDED: evmc_storage_status = 4;
pub const EVMC_STORAGE_MODIFIED_DELETED: evmc_storage_status = 5;
pub const EVMC_STORAGE_DELETED_RESTORED: evmc_storage_status = 6;
pub const EVMC_STORAGE_ADDED_DELETED: evmc_storage_status = 7;
pub const EVMC_STORAGE_MODIFIED_RESTORED: evmc_storage_status = 8;
pub type evmc_storage_status = ::std::os::raw::c_uint;
pub type evmc_set_storage_fn = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut evmc_host_context,
        address: *const evmc_address,
        key: *const evmc_bytes32,
        value: *const evmc_bytes32,
    ) -> evmc_storage_status,
>;
pub type evmc_set_transient_storage_fn = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut evmc_host_context,
        address: *const evmc_address,
        key: *const evmc_bytes32,
        value: *const evmc_bytes32,
    ),
>;
pub type evmc_get_balance_fn = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut evmc_host_context,
        address: *const evmc_address,
    ) -> evmc_uint256be,
>;
pub type evmc_get_code_size_fn = ::std::option::Option<
    unsafe extern "C" fn(context: *mut evmc_host_context, address: *const evmc_address) -> usize,
>;
pub type evmc_get_code_hash_fn = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut evmc_host_context,
        address: *const evmc_address,
    ) -> evmc_bytes32,
>;
pub type evmc_copy_code_fn = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut evmc_host_context,
        address: *const evmc_address,
        code_offset: usize,
        buffer_data: *mut u8,
        buffer_size: usize,
    ) -> usize,
>;
pub type evmc_selfdestruct_fn = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut evmc_host_context,
        address: *const evmc_address,
        beneficiary: *const evmc_address,
    ) -> bool,
>;
pub type evmc_emit_log_fn = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut evmc_host_context,
        address: *const evmc_address,
        data: *const u8,
        data_size: usize,
        topics: *const evmc_bytes32,
        topics_count: usize,
    ),
>;
pub const EVMC_ACCESS_COLD: evmc_access_status = 0;
pub const EVMC_ACCESS_WARM: evmc_access_status = 1;
pub type evmc_access_status = ::std::os::raw::c_uint;
pub type evmc_access_account_fn = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut evmc_host_context,
        address: *const evmc_address,
    ) -> evmc_access_status,
>;
pub type evmc_access_storage_fn = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut evmc_host_context,
        address: *const evmc_address,
        key: *const evmc_bytes32,
    ) -> evmc_access_status,
>;
pub type evmc_call_fn = ::std::option::Option<
    unsafe extern "C" fn(context: *mut evmc_host_context, msg: *const evmc_message) -> evmc_result,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct evmc_host_interface {
    pub account_exists: evmc_account_exists_fn,
    pub get_storage: evmc_get_storage_fn,
    pub set_storage: evmc_set_storage_fn,
    pub get_balance: evmc_get_balance_fn,
    pub get_code_size: evmc_get_code_size_fn,
    pub get_code_hash: evmc_get_code_hash_fn,
    pub copy_code: evmc_copy_code_fn,
    pub selfdestruct: evmc_selfdestruct_fn,
    pub call: evmc_call_fn,
    pub get_tx_context: evmc_get_tx_context_fn,
    pub get_block_hash: evmc_get_block_hash_fn,
    pub emit_log: evmc_emit_log_fn,
    pub access_account: evmc_access_account_fn,
    pub access_storage: evmc_access_storage_fn,
    pub get_transient_storage: evmc_get_transient_storage_fn,
    pub set_transient_storage: evmc_set_transient_storage_fn,
}
pub type evmc_destroy_fn = ::std::option::Option<unsafe extern "C" fn(vm: *mut evmc_vm)>;
pub const EVMC_SET_OPTION_SUCCESS: evmc_set_option_result = 0;
pub const EVMC_SET_OPTION_INVALID_NAME: evmc_set_option_result = 1;
pub const EVMC_SET_OPTION_INVALID_VALUE: evmc_set_option_result = 2;
pub type evmc_set_option_result = ::std::os::raw::c_uint;
pub type evmc_set_option_fn = ::std::option::Option<
    unsafe extern "C" fn(
        vm: *mut evmc_vm,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> evmc_set_option_result,
>;
pub const EVMC_FRONTIER: evmc_revision = 0;
pub const EVMC_HOMESTEAD: evmc_revision = 1;
pub const EVMC_TANGERINE_WHISTLE: evmc_revision = 2;
pub const EVMC_SPURIOUS_DRAGON: evmc_revision = 3;
pub const EVMC_BYZANTIUM: evmc_revision = 4;
pub const EVMC_CONSTANTINOPLE: evmc_revision = 5;
pub const EVMC_PETERSBURG: evmc_revision = 6;
pub const EVMC_ISTANBUL: evmc_revision = 7;
pub const EVMC_BERLIN: evmc_revision = 8;
pub const EVMC_LONDON: evmc_revision = 9;
pub const EVMC_PARIS: evmc_revision = 10;
pub const EVMC_SHANGHAI: evmc_revision = 11;
pub const EVMC_CANCUN: evmc_revision = 12;
pub const EVMC_PRAGUE: evmc_revision = 13;
pub const EVMC_OSAKA: evmc_revision = 14;
pub const EVMC_AMSTERDAM: evmc_revision = 15;
pub const EVMC_EXPERIMENTAL: evmc_revision = 16;
pub const EVMC_MAX_REVISION: evmc_revision = 16;
pub const EVMC_LATEST_STABLE_REVISION: evmc_revision = 14;
pub type evmc_revision = ::std::os::raw::c_uint;
pub type evmc_execute_fn = ::std::option::Option<
    unsafe extern "C" fn(
        vm: *mut evmc_vm,
        host: *const evmc_host_interface,
        context: *mut evmc_host_context,
        rev: evmc_revision,
        msg: *const evmc_message,
        code: *const u8,
        code_size: usize,
    ) -> evmc_result,
>;
pub const EVMC_CAPABILITY_EVM1: evmc_capabilities = 1;
pub const EVMC_CAPABILITY_EWASM: evmc_capabilities = 2;
pub const EVMC_CAPABILITY_PRECOMPILES: evmc_capabilities = 4;
pub type evmc_capabilities = ::std::os::raw::c_uint;
pub type evmc_capabilities_flagset = u32;
pub type evmc_get_capabilities_fn =
    ::std::option::Option<unsafe extern "C" fn(vm: *mut evmc_vm) -> evmc_capabilities_flagset>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct evmc_vm {
    pub abi_version: ::std::os::raw::c_int,
    pub name: *const ::std::os::raw::c_char,
    pub version: *const ::std::os::raw::c_char,
    pub destroy: evmc_destroy_fn,
    pub execute: evmc_execute_fn,
    pub get_capabilities: evmc_get_capabilities_fn,
    pub set_option: evmc_set_option_fn,
}
