[alias]
cl = "clippy --workspace --all-features --all-targets"
docs = "doc --workspace --all-features --no-deps --document-private-items"
cli-jit = "nextest run -p evm2-cli --features jit --bin evm2"
t = "nextest run --workspace"
st = "nextest run --workspace --ignore-default-filter"
eest-jit = "nextest run -p evm2-eest --features jit --lib --ignore-default-filter"
st-jit = "nextest run -p evm2-eest --features jit --test eest --ignore-default-filter"
