name: Benchmark

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: "sccache"
  RUSTFLAGS: -Csymbol-mangling-version=v0

jobs:
  codspeed:
    runs-on: depot-ubuntu-latest
    permissions:
      contents: read
    environment: codspeed
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install LLVM
        run: .github/scripts/install_llvm.sh ubuntu
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      - uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          cache-on-failure: true
          cache-bin: false
      - name: Install cargo-codspeed
        uses: taiki-e/install-action@7f4eb899022d8fe70b20c4f3de697aa85c309026 # v2.85.11
        with:
          tool: cargo-codspeed
      - name: Build the benchmark target
        run: cargo codspeed build --profile profiling -p evm2-cli --features jit --bench evm
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@4296e51e7041e24dadb86d1d6e8b9320d223dbe8 # v5.0.3
        with:
          run: cargo codspeed run -p evm2-cli --bench evm
          mode: instrumentation
          token: ${{ secrets.CODSPEED_TOKEN }}
