name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.kind }}${{ matrix.fixture && format(' {0}', matrix.fixture) || '' }} +${{ matrix.rust }} ${{ matrix.os }} ${{ matrix.flags }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        kind: ["test", "eest"]
        os: [
          "ubuntu-latest",
          # "macos-latest",
          # "windows-latest",
        ]
        rust: [
          "stable",
          "nightly",
          # "1.95", # MSRV
        ]
        flags: [
          # No features
          "--no-default-features",
          # Default features
          "",
        ]
        fixture: [""]
        include:
          # All features
          - kind: "test"
            os: "ubuntu-latest"
            rust: "nightly"
            flags: "--all-features"
          - kind: "eest"
            os: "ubuntu-latest"
            rust: "nightly"
            flags: "--all-features"
          # - kind: "test"
          #   os: "macos-latest"
          #   rust: "nightly"
          #   flags: "--all-features"
          # - kind: "eest"
          #   os: "macos-latest"
          #   rust: "nightly"
          #   flags: "--all-features"
          # - kind: "test"
          #   os: "windows-latest"
          #   rust: "nightly"
          #   flags: "--features nightly" # Some C libraries don't support MSVC.
          # - kind: "eest"
          #   os: "windows-latest"
          #   rust: "nightly"
          #   flags: "--features nightly" # Some C libraries don't support MSVC.
          # Devnet
          # - kind: "eest"
          #   fixture: "devnet"
          #   os: "ubuntu-latest"
          #   rust: "stable"
          #   flags: ""

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: rui314/setup-mold@v1
        if: runner.os == 'Linux'
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@nextest
      - uses: astral-sh/setup-uv@v7
        if: ${{ matrix.kind == 'eest' || matrix.flags == '--all-features' }}
      - name: Download EEST fixtures
        if: ${{ matrix.kind == 'eest' || matrix.flags == '--all-features' }}
        shell: bash
        run: |
            if [[ "${{ matrix.fixture }}" == "devnet" ]]; then
              export DEVNET_VERSION="snobal-devnet-6%40v1.1.0"
              export DEVNET_TAR="fixtures_snobal-devnet-6.tar.gz"
              export EVM2_STATETEST_DEVNET_ONLY=1
            fi
            ./scripts/setup_test_fixtures.py
      - name: ${{ matrix.kind }}
        shell: bash
        run: |
            extra_flags=()
            if [[ "${{ matrix.kind }}" == "eest" ]]; then
              extra_flags+=(-p evm2-eest --ignore-default-filter)
            elif [[ "${{ matrix.flags }}" == "--all-features" ]]; then
              extra_flags+=(--ignore-default-filter)
            fi
            if [[ "${{ matrix.fixture }}" == "devnet" ]]; then
              export EVM2_STATETEST_ROOT="test-fixtures/devnet/state_tests"
              export EVM2_BLOCKCHAINTEST_ROOT="test-fixtures/devnet/blockchain_tests"
            fi
            cargo nextest run --workspace --no-fail-fast ${{ matrix.flags }} "${extra_flags[@]}"
      - name: doctest
        if: ${{ matrix.kind == 'test' }}
        run: cargo test --workspace ${{ matrix.flags }} --doc

  wasm:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: check
        run: cargo build -p evm2 --target wasm32-unknown-unknown --no-default-features

  no-std:
    name: no_std ${{ matrix.target }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        target: ["riscv32imac-unknown-none-elf", "riscv64imac-unknown-none-elf"]
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: check
        run: cargo build -p evm2 --target ${{ matrix.target }} --no-default-features

  feature-checks:
    name: features ${{ matrix.flags }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        flags: ["", "--all-targets"]
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: rui314/setup-mold@v1
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: cargo hack
        run: cargo hack check --workspace --each-feature --skip nightly ${{ matrix.flags }}

  feature-propagation:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: rui314/setup-mold@v1
      - uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: zepter
      - name: Eagerly pull dependencies
        run: cargo generate-lockfile
      - run: zepter run check

  examples:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Check examples
        run: cargo build --workspace --examples

  typos:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@v1

  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - run: cargo clippy --workspace --all-targets --all-features

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Build documentation
        run: cargo doc --workspace --all-features --no-deps --document-private-items

  fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  deny:
    uses: tempoxyz/ci/.github/workflows/deny.yml@main

  ci-success:
    name: ci success
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test
      - wasm
      - no-std
      - feature-checks
      - feature-propagation
      - examples
      - typos
      - clippy
      - docs
      - fmt
      - deny
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
